rpiambulance/website

index.html
js/controllers/EditMemberCtrl.js
js/controllers/MainCtrl.js

This adds a navigation bar item for the scheduling coordinator. It seems to work pretty well, however it seems like the navbar gets stuck when the user logs out. I think it's because the logout process isn't completing correctly and is a side effect of the issue I have open that clicking home logs the user out. This fixes #35

Adds a navbar for the scheduling coordinator.

---

js/appRoutes.js
js/controllers/EventCtrl.js
js/controllers/GameCtrl.js
js/controllers/GamesEventsCtrl.js
js/controllers/MainCtrl.js
views/event.html
views/game.html
views/games-events.html

Closes #14.
This makes it so that when hitting any of the buttons above the calendar, it alters the URL, pushing it into the browser history so that when you click on an event/game, you can then hit back and be taken back to where you were on the calendar. The downside is that it does add every action so if you change the month 5 times, you'll have to hit the back button 5 times before you start hitting where you were before the calendar.

Calendar back

---

views/night-crews.html

Closes #23
What was happening here was that this sort was doing a lexicographical sort using the date as a string, which meant that '01' < '12'. Since the data that's returned from the API is always in the right order, there's not much reason to need to order things here as well.

Fix ordering of crews around end of year rollover

---

js/controllers/GamesEventsCtrl.js

This also makes changing between different views/dates more stable as well by removing a potential race condition in having two separate `$watch` clauses that trigger the same secondary function.

Fix for clicking certain timespans on calendar

---

views/home.html

Fixed display issue where "Other Agencies" section text couldn't be seen because of the dark background.

Difficulty Seeing "Other Agencies" Section Text

---

css/main.css
index.html
views/home.html

This fixes a handful of errors and contrast things as pointed out by https://wave.webaim.org/ for accessibility:
* Update the FG/IG/Reddit icons to have labels (instead of being blank links)
* Update footer "partner" images to have alt and title texts
* Update color of links in footer to have much better contrast (up from 3.62:1 to 7.06:1)

Fix accessibility stuff on homepage

---

.get_event_info.php
.get_game_info.php

Fixes the `startObj`s and `endObj`s being invalid due to [something weird](https://jira.mariadb.org/browse/MDEV-20695) in MariaDB.
Tested on the SQL server and a valid epoch value is returned.

Fix epoch stuff

---

Dockerfile

When installing packages where `zip` and `unzip` are missing, Docker outputs this as part of the build log:
```
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 13 installs, 0 updates, 0 removals
Failed to download phpseclib/phpseclib from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
Now trying to download from source
- Installing phpseclib/phpseclib (2.0.21): Cloning 9f1287e68b from cache
Failed to download psr/log from dist: The zip extension and unzip command are both missing, skipping.
...
```
where this is repeated for many packages that attempt to be installed.

add zip and unzip to website Dockerfile for composer package installation

---

slack-blog/index.html

This will allow `https://rpiambulance.com/slack-blog` to be used as a redirect. Instagram doesn't allow for hyperlinks in their captions, so this will allow our near-future post's viewers the ability to type in a quick URL to get to the blog.

Add redirect to use on insta

---

.crews.php
Dockerfile
views/night-crews.html

Changes the effective turnover time to 4pm Sunday. I also cleaned up an undefined offset error and added the reasons you may be inelegible for a spot.

Make it so you're forced to wait until 4pm on Sunday to signup

---

index.html

This fixes the flicker of `Welcome, {{user}}!` in the header while angular loads. It uses the standard [`ngCloak`](https://docs.angularjs.org/api/ng/directive/ngCloak) directive to accomplish it.
Now, for a user that is not logged in, nothing will be shown, and for a user that is logged in, it will show the welcome line.

do not show welcome line in header until angular loads

---

.crews.php
.defaults.php
.docker/mysql/default.sql
.docker/mysql/schema.sql
.modify_schedule.php
js/controllers/EditDefaultCtrl.js
js/controllers/ModifyScheduleCtrl.js
js/controllers/NightCrewsCtrl.js
slack-whoson.php
views/edit-default.html
views/modify-schedule.html
views/night-crews.html

This adds a `dutysup` row to the `crews` table and the `default_crews` table in the database. It also adjusts the `Modify Schedule` and `Edit Default Schedule` pages on the website to show a column for Duty Supervisor.
Since `js/controllers/NightCrewsCtrl.js` and `js/controllers/ModifyScheduleCtrl.js` both used the same `loadCrews()` function to display the crew, the DS was appearing on the Night Crews page, I added a second function `loadCrewsNoDS` that removes the DS column from the Night Crews Page. Alternatively, it could be removed when being displayed, leaving it in the array, which would only require one function. Let me know if you think that'd be better!

Add duty supervisor to database and website (and support for /whoson)

---

.edit_member.php

This will allow for adding/removing the previously broken coordinator positions (CPR, Webmaster, QA/QI, and Dev Team). Webmaster is still also tied into website Admin status (any non-officer/coordinator with full admin on the website will be shown as a webmaster).

Fix changing of coordinators in edit member page

---

js/controllers/EditMemberCtrl.js
js/controllers/MemberListCtrl.js

With this, a member can be a website admin without automatically being shown as a webmaster on the member list. Instead, the webmaster position can be controlled using the dropdown in the edit member (or directly through the database).

Separate webmaster from website admin

---

.crews.php

The P-CC/P-D check for a trainer was overriding a member's higher (CC, CC-T, FR-CC, D, D-T) credential if they still had the probationary position checked. It would show them "No [CC/D]-T on" and prevent them from signing up if they had both the probationary and the higher position.

Full CC/Driver doesn't need CC-T on to sign up

---

js/controllers/AddEventCtrl.js

The datepicker for creating and editing events had a maxDate set which only allowed users to select dates before 2020-05-22. Dates beyond then could be manually entered, but not selected via the popup. This removes the maxDate and allows selection of any date.

Fix event datepicker

---

.crews.php

Changes time that a member can bypass the 2-week rotation and sign up for a same-day night crew from 1600 to 1200

Change day-of signup time from 1600 to 1200

---

.crews.php

This fixes the issue that was discussed in #110 but wouldn't have been fixed with just changing `7` to `14`.
Basically, `$tableloop` is `0` or `1` depending on which week is being modified. That is, if you're trying to sign up for a night crew _this week_, `$tableloop` will be `0`, and day `0` is indexed to the Sunday of this week. In that case, we want to look _forward_ to the end of _next week_ to ensure you're not riding so as to enforce the "every two week" policy that's currently in place. ~Note that this code will have to be changed if/when that policy is reverted to "every week."~ I also added a boolean for a two- vs. one-week rotation.
Conversely, if you're trying to sign up for a crew _next week_, `$tableloop` is `1`, and day `0` is indexed to the Sunday of next week. As such, we …

add check for which week is being worked on

---

js/controllers/ModifyScheduleCtrl.js

Allows the current Captain to be selected on the schedule as the Duty Supervisor even if not credentialed as such

Captain as acting duty supervisor

---

index.html
js/controllers/DOHResourcesCtrl.js
js/controllers/FAQCtrl.js
js/controllers/RENSCOResourcesCtrl.js
views/home.html

Fixed a few dead links throughout the website:
The FAQ had a dead link which was supposed to point to information about reciprocity. As Tom pointed out that this page is more public-facing (members likely wouldn't be on the FAQ), I changed this link to the NYS reciprocity website instead of the member-only page on reciprocity.
The home page had two dead links to Rensselaer County Public Safety (one on the logo, another under "Other Agencies." Swapped these out.
The DOH Resources page had two dead links as well, swapped those out.
Finally, the Rensselaer County Resources page had a dead link as well as one that didn't seem to match the following description. Swapped that one out for a new link and altered the description.

Fixing Dead Links

---

views/edit-member.html

Fixes #44. Angular docs [say](https://docs.angularjs.org/api/ng/directive/ngChecked) use of "ng-model" and "ng-checked" together can create the unexpected behavior. Changed to use "ng-true-value" and "ng-false-value" to properly sync the checkboxes.

Fix #44 - Edit Member Behavior

---

js/controllers/CrewChiefTrainingCtrl.js

A line in CrewChiefTrainingCtrl was missing a `'` causing the website to break/not load.

CrewChiefTrainingCtrl breaks website

---

.add_game.php
.docker/mysql/schema.sql
js/controllers/AddEventCtrl.js
js/controllers/GameCtrl.js
views/add-event.html
views/game.html

Adds the ability to lock games (not events) from signups by editing the game on the calendar (request #163). This will prevent anybody from signing up or switching their role, but does allow people to drop from a locked game.
The following SQL statement will need to be run on the production DB to add the new column to the `games` table:
```
ALTER TABLE `games` ADD `locked` TINYINT(1) NOT NULL DEFAULT '0' AFTER `location`;
```
Here is a preview of what it looks like:
<p align="center">
</p>

Lock game attendance

---

slack-link.php

This only changes "Positions: <etc>" in a `/memberinfo @person` response to "Credentials: <etc>" which is more indicative of what those data points actually are.

Change "positions" to "credentials"
