front_events.php

Fixed issue with upcoming events showing past events and added future support for the hide database field and its future use in public and private events.

Fixed upcoming events showing past events.

---

css/main.css

See https://github.com/rpiambulance/website/issues/1

Fixed the remove from crew button being misaligned with name

---

css/main.css

Fix link being off in second carousel image

---

js/controllers/CommunicationsCtrl.js
js/controllers/DriverTrainingCtrl.js
js/controllers/MutualAidCtrl.js
js/controllers/SupervisorTrainingCtrl.js
js/controllers/TextMessageDispatchCtrl.js
views/member-list.html

New 800 system not yet updated

Fixed many visible typos and updated radio information.  

---

js/controllers/CommunicationsCtrl.js

Also did some style changes for VHF stuff.

Changed 800 info to new digital system.

---

js/controllers/LoginCtrl.js
views/login.html

Shows the following alert to users when they hit the forget login link on the login page:
This is instead of just taking the user to the homepage, which is exactly helpful.

Add alert for hitting forget password

---

js/app.js

I forgot to commit this file in my last PR.

Fix the if check for undefined variable in js/app.js

---

.crews.php
.delete_event.php
.delete_game.php
.drop_event.php
.drop_event_other_member.php
.drop_game.php
.drop_game_other_member.php
.edit_self.php
.edit_self_pass.php
.functions.php
.get_event_info.php
.get_game_info.php
.get_if_admin.php
.get_user_metadata.php
.logout.php
.signup_event.php
.signup_game.php
member_table.php

Proper use session_id and session_start

---

js/controllers/EditDefaultCtrl.js
js/controllers/EditMemberCtrl.js
js/controllers/MemberListCtrl.js
js/controllers/ModifyScheduleCtrl.js

Add session_id parameters to all uses of member_table.php

---

.crews.php
index.html
js/app.js
js/controllers/GamesEventsCtrl.js
js/controllers/NightCrewsCtrl.js
js/services/AuthService.js
js/services/DateService.js
views/night-crews.html

Implement previous/next week buttons on Night Crews page

---

.crews.php
js/controllers/NightCrewsCtrl.js

add dob check to crew eligibility

---

.gitignore
index.html
views/add-member.html
views/edit-member.html

This should fix #49, though admittedly, I have no real way of testing it. Let me know if anything's really wrong.

Form validation

---

.login.php
.logout.php

More secure sessions and fixed logout

---

.add_event.php
.add_game.php
.delete_event.php
.delete_game.php
.functions.php
.gcal.php
.gitignore
css/main.css
views/games-events.html

Syncs RPIA's calendar with google calendar.

Google Calendar sync with RPIA Calendar

---

js/controllers/GameCtrl.js

I spelled ambulance in the secondlt email correctly not allowing people to email the 2nd lt back.

Spell ambulance correctly.

---

.crews.php

Fixes the date interval being incorrect when we have two week rotations.

Fixes the negative index issue

---

js/controllers/AddEventCtrl.js

fix displaying start and end time when editing event or game

---

js/controllers/AttendantTrainingCtrl.js
js/controllers/CommunicationsCtrl.js
js/controllers/ConstitutionCtrl.js
js/controllers/CrewChiefTrainingCtrl.js
js/controllers/DriverTrainingCtrl.js
js/controllers/InServiceTrainingCtrl.js
js/controllers/MinutesCtrl.js
js/controllers/MiscFormsCtrl.js
js/controllers/NewMembersTrainingCtrl.js
js/controllers/RENSCOResourcesCtrl.js
js/controllers/SOPCtrl.js
js/controllers/SupervisorTrainingCtrl.js

Lots of Google embedded folder changes

Fix Google Drive embedded folder links

---

index.html
js/app.js
js/appRoutes.js
js/controllers/MainCtrl.js
js/controllers/SOGCtrl.js
views/sog.html

Fixes #94. Updates the website page to match the updated RPIA documents.

Update SOPs to SOGs

---

.github/workflows/main.yml

instead of making individual script secrets for every repo

Use organization secret for script

---

js/controllers/SupervisorTrainingCtrl.js

Caleb isn't a duty sup now that he isn't captain, and Everest is credentialed as a duty sup now. Put them in alphabetical order (for Jacob)

Correct duty sup list

---

js/controllers/LoginCtrl.js

Correct grammar in login error message

Fix Login Error

---

js/controllers/SupervisorTrainingCtrl.js

Per C1 request to match SOGs and update caps.

Update Duty Supervisor description

---

js/controllers/BylawsCtrl.js
js/controllers/MainCtrl.js

Issue #158. No longer 404s, fixed typos noted by @CKegel .

Fixed broken bylaws link & added page to resource dropdown

---

air-oos.php

Allows functionality for a new feature for [AIR](https://github.com/techinems/air), still in progress over there

add functionality for air oos features

---

js/controllers/CrewChiefTrainingCtrl.js
js/controllers/DriverTrainingCtrl.js

The current training requirements as listed on the website have not been updated to reflect several years of SOG changes. This PR corrects spelling errors and aligns the training pages with the 23-01 revision of the SOGs.

Update training requirements as listed on the website

---

index.html

Replace the donation link with our new RU Impact link.

Update the donation link

---

index.html

Update the donate link to be the new static donate.rpiambulance.com link

Update donate button link.

---

js/controllers/OfficersCtrl.js

Adds Fall 2024, Winter 2024, and Spring 2025 officer boards.

Adds new officer boards
